### PR TITLE
use official fullstack eslint config

### PR DESCRIPTION
**Pull request by glebec**
This PR integrates [eslint-config-fullstack](https://github.com/fullstackacademy/eslint-config-fullstack) into FSG. I suggest that if you disagree with any of the settings in that config, you either make a PR to that project, or override / extend some of the rules in the `.eslintrc.json` — using the Fullstack config as a base but customizing it specifically for FSG.

### CODE REVIEW

**Comment by glebec** [comment]
I just realized we might also have to upgrade `gulp-eslint` in order to get ESLint 3 support.

**Comment by omriBernstein** [comment]
@glebec: Have you confirmed whether or not we'll need to update `gulp-eslint`?

**Comment by glebec** [comment]
Yes, we will. I am updating the PR, will at-mention you when it's fixed (later this weekend).

**Comment by glebec** [comment]
@omriBernstein PR is ready now. I edited the project formatting a bit in order to actually pass the ESLint rules that became activated as a result of fixing this.

**Comment by omriBernstein** [comment]
Big 👍 you the best. Merging now.

**Comment by glebec** [comment]
Thanks! Also, I forgot to mention this PR fixes a small bug in the Twitter OAuth I found incidentally.

**Pull request merged**
